pipelines:
  - name: Matrix_Demo_Pipeline
  steps:
      - name: Begin_Matrix
        type: PreMatrix
        configuration:
        execution:
          onExecute:
            - echo "Executing PreMatrix step...."
            - echo "File got created in fanout step" >> input.txt
      
      - name: Matrix_Example
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: Begin_Matrix
        stepletMultipliers:
          environmentVariables:             # Sets of environment variables for steplets
            - animal:    dog                # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat               # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead          
              
          runtimes:
            - type: image
              image:
                auto:
                  language: java
                  versions:
                    - 13.0

            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0

            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 12.14.0

            - type: image
              image:
                auto:
                  language: cpp
                  versions:
                    - 8.0.0
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - cat ./fanout_demo/input.txt
            - mkdir -p files
            - echo "-----"
            - echo "File got created in steplet ${steplet_number}" >> ./files/${steplet_number}.txt
            - echo "Running on runtime ${step_image_name}:${step_image_tag}" >> ./files/${steplet_number}.txt
            - echo "-----"
            - set_step_var matrix_envs "animal = ${animal}, mineral = ${mineral}, vegetable = ${vegetable}"

      - name: Finish_Matrix
        type: PostMatrix
        configuration:
          inputResources:
            - name: MyRepo
          inputSteps: 
            - name: Matrix_Example
        execution:
          onExecute:
            - echo "Executing PostMatrix step"
            - echo "Matrix state files..."
            - ls -l Matrix_Example/files/
            - cat Matrix_Example/files/*
            - echo "FanOut state files..."
            - ls -l Matrix_Example/fanout_demo
            - get_step_var Matrix_Example matrix_envs
