#resources:
#  - name: CompletedBuild
#    type: BuildInfo
#    configuration:
#      sourceArtifactory:    art
#      buildName:            ExampleBuild
#      buildNumber:          1
      
pipelines:
  - name: Matrix_Single_Pipeline
    steps:
     
      - name: matrix_example
        type: Matrix
        stepMode: Bash
        configuration:
          inputResources:
            - name: CompletedBuild
        stepletMultipliers:
          environmentVariables:             # Sets of environment variables for steplets
            - animal:    dog                # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat               # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead          
              
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - echo "Triggered on build of ${res_CompletedBuild_buildName}:${res_CompletedBuild_buildNumber}"
            - echo "Env variables animal = ${animal}, mineral = ${mineral}, vegetable = ${vegetable}"
